version: "3.8"

services:
  chat_backend:
    image: mithunvasanth/chat-backend  # Pull image directly from Docker Hub
    ports:
      - "5213:5213"  
    environment:
      - PYTHONUNBUFFERED=1  

  frontend:
    image: mithunvasanth/frontend  # Pull image directly from Docker Hub
    ports:
      - "5261:80" 
    depends_on:
      - chat_backend
